#测试环境
server:
  port: 14914
#  servlet:
#    encoding:
#      charset: GBK

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  banner:
    image:
      location: classpath:banner_fozu.txt
  datasource:
    url: jdbc:mysql://localhost:3306/springboot2studysql?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql
      hibernate:
        dd1-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect


com:
  dokstudio:
    canghaisangtian: cangHaiSangTian
    renjianzhengdao: renJianZhengDao

#mycar:
#  brand: BYD
#  price: 120000
##debug: true

## yaml表示以上对象
#person:
#  userName: zhangsan
#  boss: false
#  birth: 2019/12/12 20:12:33
#  age: 18
#  pet:
#    name: tomcat
#    weight: 23.4
#  #  interests: [篮球,游泳]
#  interests:
#    - 篮球
#    - 游泳
#  #  animal: [阿猫,阿狗]
#  animal:
#    - jerry
#    - mario
#  score:
#    english:
#      first: 30
#      second: 40
#      third: 50
#    math: [131,140,148]
#    chinese: {first: 128,second: 136}
#  salarys: [3999,4999.98,5999.99]
#  allPets:
#    sick:
#      - name: tom
#        weight: 22
#      - {name: jerry,weight: 47}
#    health: [{name: mario,weight: 47}]
